### ISSUE TITLE
Question: How do I get the KKGridViewCell* from these functions?

### ISSUE THREAD

**Issue by ghost** [kolinkrewinkel/KKGridView#119]
```
- (void)gridView:(KKGridView *)gridView didSelectItemAtIndexPath:(KKIndexPath *)indexPath
- (void)gridView:(KKGridView *)gridView didDeselectItemAtIndexPath:(KKIndexPath *)indexPath
```

I want to get the cell so that I can put a badge on them when I select them (the checkmark that is still not working :p) so that it can look like Apple's Photo Library app.

**Comment by jonsterling** [comment]
Good question. It's possible that in the future, we'll add a method to lookup cells by their index paths, but I don't think it's quite necessary at the moment. That's neither here nor there, though, since accessing the cell for the purpose of adding a checkmark is neither a correct nor robust solution to your problem.

Instead, you should be handling this declaratively from within `-gridView:cellForItemAtIndexPath:`:

``` objc
cell.accessoryType = cell.selected ? KKGridViewCellAccessoryTypeCheckmark 
                                   : KKGridViewCellAccessoryTypeNone;
```

Hope this helps! I'm going to close this, but if my answer didn't help, let me know and I'll reopen it until your problem is solved.
